CREATE TABLE IF NOT EXISTS urls (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP(0) NOT NULL
);

CREATE TABLE IF NOT EXISTS checks (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    url_id INT NOT NULL REFERENCES urls (id) ON DELETE CASCADE,
    h1 VARCHAR(255),
    code INT,
    title VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP(0) NOT NULL
);