<?php

//dump($errors);
//dump($flash);
//dump($url);
//dump($checks);

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">

</head>

<body class="min-vh-100 d-flex flex-column">

<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="/">Главная</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<?php if (isset($flash['success'])) : ?>
<div class="alert alert-success" role="alert">
    <?= htmlspecialchars($flash['success'][0]) ?>
</div>
<?php endif; ?>


<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= htmlspecialchars($url->getId() ?? '') ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= htmlspecialchars($url->getName() ?? '') ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= htmlspecialchars($url->getCreatedAt() ?? '') ?></td>
                </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= htmlspecialchars($url->getId() ?? '') ?>/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <thead>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($checks as $check): ?>
            <tr>
                <td><?= htmlspecialchars($check->getId() ?? '') ?></td>
                <td><?= htmlspecialchars($check->getCode() ?? '') ?></td>
                <td><?= htmlspecialchars($check->getH1() ?? '') ?></td>
                <td><?= htmlspecialchars($check->getTitle() ?? '') ?></td>
                <td><?= htmlspecialchars($check->getDescription() ?? '') ?></td>
                <td><?= htmlspecialchars($check->getCreatedAt() ?? '') ?></td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.min.js" integrity="sha384-VQqxDN0EQCkWoxt/0vsQvZswzTHUVOImccYmSyhJTp7kGtPed0Qcx8rK9h9YEgx+" crossorigin="anonymous"></script>
</body>
</html>
