<div class="container-lg mt-3">
    <h1>Сайты</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
            <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($lastChecks as $lastCheck) : ?>
                <tr>
                    <td><?= htmlspecialchars($lastCheck['id'] ?? '') ?></td>
                    <td>
                        <a href="/urls/<?= htmlspecialchars($lastCheck['id'] ?? '') ?>"><?= htmlspecialchars($lastCheck['name'] ?? '') ?></a>
                    </td>
                    <td><?= htmlspecialchars($lastCheck['created_at'] ?? '') ?></td>
                    <td><?= htmlspecialchars($lastCheck['status_code'] ?? '') ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
