<div class="container-lg mt-3">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
            <h1 class="display-3">Анализатор страниц</h1>
            <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
            <form action="/urls" method="post" class="row g-2" required>
                <div class="col-12 col-md-8">
                    <label for="text" class="visually-hidden">Url для проверки</label>

                    <input
                            type="text"
                            name="url[name]"
                            value="<?= htmlspecialchars($url ?? '') ?>"
                            class="form-control form-control-lg"
                            placeholder="https://www.example.com"
                            required
                    >

                    <?php if (isset($errors['name'])) : ?>
                        <div><?= htmlspecialchars($errors['name']) ?></div>
                    <?php endif; ?>
                </div>
                <div class="col-12 col-md-4 d-grid d-md-block">
                    <input type="submit" class="btn btn-primary btn-lg w-100 text-uppercase" value="Проверить">
                </div>
            </form>
        </div>
    </div>
</div>
